### ISSUE TITLE
Feature Request : Project Level Metrics

### ISSUE THREAD

**Issue by theapache64** [PatilShreyas/compose-report-to-html#12]
**Expectation**

Simply running `composeReport2Html` should generate a project level metrics :)

**Comment by PatilShreyas** [comment]
I tried developing Gradle plugin for this earlier but was unable to make it. But yes, it's in the plan. Thanks

**Comment by PatilShreyas** [comment]
@theapache64 we have Gradle plugin now: https://patilshreyas.github.io/compose-report-to-html/use/using-gradle-plugin/
