### ISSUE TITLE
support compose 1.7.0 please

### ISSUE THREAD

**Issue by RavenLiao** [PatilShreyas/compose-report-to-html#128]
# Issue Summary:

After upgrading the following dependencies:
```
compose-bom to version 2024.09.02
kotlin to version 2.0.20
````
I encountered an error when running the Gradle task developDebugComposeCompilerHtmlReport.

Error Details:

```
Unexpected JSON token at offset 659: Expected numeric literal at path: $['featureFlags']
JSON input: .....mbdas": 24,
  "featureFlags": {
    "StrongSkipping": true,
.....

````

# Additional Information:

I was able to reproduce this issue in two different projects.

**Comment by PatilShreyas** [comment]
Thanks for reporting the issue @RavenLiao. Let me plan it this weekend.
