### ISSUE TITLE
Allow the Gradle plugin to be used with Jetbrains Compose

### ISSUE THREAD

**Issue by eygraber** [PatilShreyas/compose-report-to-html#33]
Compiler metrics works if using the Jetpack compiler artifact with Jetbrains compose. I'm still not sure if they work with the Jetbrains compiler artifact.

**Comment by PatilShreyas** [comment]
@eygraber Thanks, will definitely check how can this plugin be enabled for JetBrains Compose projects.

**Comment by maltsev-gorskij** [comment]
Hello. It there any progress on this one? Really relevant for me too.

**Comment by PatilShreyas** [comment]
Fixed and released in `v1.4.0`.
