### ISSUE TITLE
getting org/gradle/configurationcache/extensions/CharSequenceExtensionsKt error

### ISSUE THREAD

**Issue by karandeepsingh-cred** [PatilShreyas/compose-report-to-html#34]
after integrating the gradle plugin I am getting the following error
A problem occurred configuring project ':app'.
> Could not create task ':app:releaseComposeCompilerHtmlReport'.
   > org/gradle/configurationcache/extensions/CharSequenceExtensionsKt

**Comment by PatilShreyas** [comment]
Could you share a sample project in which you're getting a issue?

**Comment by PatilShreyas** [comment]
Thanks, @karandeepsingh-cred for raising this. This has been fixed and released in `v1.0.0`
