### ISSUE TITLE
Conflict with Apollo GraphQL

### ISSUE THREAD

**Issue by leffsu** [PatilShreyas/compose-report-to-html#42]
Greetings! Thank you for this amazing library but I can't seem to get it working in project with Apollo GraphQL (AppSync SDK).

Getting the following error executing devDebugComposeCompilerHtmlReport:

`Cannot serialize Kotlin type com.apollographql.apollo.compiler.ir.CodeGenerationIR. Reflective serialization of Kotlin classes without using kotlin-reflect has undefined and unexpected behavior. Please use KotlinJsonAdapterFactory from the moshi-kotlin artifact or use code gen from the moshi-kotlin-codegen artifact.`

Could you attempt to use KotlinJsonAdapterFactory or allow us to configure if we want to use Moshi or Gson?

Thank you!

**Comment by PatilShreyas** [comment]
Thanks @leffsu for raising this issue. We'll definitely fix this issue on priority. Meanwhile, could you please how to reproduce this or if you can share a sample project, that would be a great help.

**Comment by leffsu** [comment]
Sure, @PatilShreyas! https://github.com/leffsu/Compose_Metrics_report_Issue

New Android Studio create project flow is a mess so it worked for me with JDK 17 but 13 should work fine too. Running debugComposeCompilerHtmlReport produces the same error. 

_Re-download dependencies and sync project (requires network)_ button doesn't help.

**Comment by PatilShreyas** [comment]
Thanks, @leffsu for sharing the sample. It's easy to test this issue very quickly due to this. It's been fixed in v1.0.1.
