### ISSUE TITLE
Composibles without issues are populated with composibles with issues

### ISSUE THREAD

**Issue by leffsu** [PatilShreyas/compose-report-to-html#46]
Greetings!

Looking at report, I see some bits which are marked as unstable (VMs, Uri, etc). But these widgets are in the "Composibles without issues".

Is this behavior correct?

![image](https://user-images.githubusercontent.com/30364628/226608730-9111d45d-6f31-47cd-b5f7-322ce6dd2bd5.png)

**Comment by PatilShreyas** [comment]
If you have any questions in future, feel free to discuss them in the discussions forum: https://github.com/PatilShreyas/compose-report-to-html/discussions

It would be helpful for other visitors as well 😃.
